services:
  frontend:
    image: frontend
    container_name: frontend

  backend:
    image: backend
    container_name: backend

  redis:
    image: redis
    container_name: redis

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./database:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - 127.0.0.1:80:80
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
